### ISSUE TITLE
[Feature Request] - Status summarization display

### ISSUE THREAD

**Issue by SirFancyBacon** [SirFancyBacon/baconcraft#3]
Either add it to the hover display of the "equipment" item.
Or make an option for "equipment" to open a container inventory that displays various summarized information on hover.

**Comment by SirFancyBacon** [comment]
I can remove the scoreboard and or make it togglable if a separate screen is used

**Comment by metruzanca** [comment]
> I can remove the scoreboard and or make it togglable if a separate screen is used

The stats there are cool, but if you have say a minimap you'll have coords in 2 different places which just leads to clutter.

**Comment by SirFancyBacon** [comment]
Right, the only problem is there is no minimap plugin; since that requires clientside modification.

I suppose i can find a minimap plugin that i prefer and support it... But i try to have a minimal mods as possible; Fabric only has so many since so many are required to replace Optifine.

**Comment by SirFancyBacon** [comment]
GOOP plugin to be updated with this feature to allow for lore to be parsed for placeholders.

In this new menu i will add the option to turn the scoreboard off and on

**Comment by SirFancyBacon** [comment]
Implemented; Toggle for SimpleScore not in place yet.
