### ISSUE TITLE
[Bug]: Silver Sword Undead bonus doesn't work

### ISSUE THREAD

**Issue by metruzanca** [SirFancyBacon/baconcraft#6]
As title, bonus doesn't seem to be applied when used agaist zombies, skeletons(vanilla) and wither skeletons. Not sure if it works on the added mobs e.g. the archers or the other types of zombies.

**Comment by metruzanca** [comment]
Can confirm, does work on custom mobs

**Comment by metruzanca** [comment]
Just not vanilla

**Comment by SirFancyBacon** [comment]
Long story short it cannot work on vanilla; But vanilla mobs shouldn't be spawning...

Do you know under what conditions you found them in?

**Comment by SirFancyBacon** [comment]
Not actually a bug; the issue is vanilla mobs spawn.
